name: build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Setup Arduino Core for Arduino Due board
      run: |
        arduino-cli core update-index
        arduino-cli core install arduino:sam@1.6.11

    - name: Install 
      run: arduino-cli lib install "DueFlashStorage@1.0.0"

    - name: Compile
      run:  |
        echo 'Run number ${{ github.run_number }}'
        arduino-cli compile --export-binaries --fqbn arduino:sam:arduino_due_x ./linnstrument-firmware.ino
        mv build/arduino.sam.arduino_due_x linnstrument-fork-build${{ github.run_number }}.bin

    - name: Publish Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.bin
    
    - name: Diagnose
      run:  |
        echo 'Run number ${{ github.run_number }}'
        echo 'build/ contents:'
        ls build/
        echo '. contents:'
        ls
        echo '${{ github.workspace }} contents:'
        ls ${{ github.workspace }}
          
